region = "eu-west-1"
nginx_bucket_name      = "nginx-bucket-luke"
nginx_ec2_role         = "ec2-nginx-access"
nginx_instance_profile = "ec2-nginx-instance-profile"
nginx_log_group = "nginx-log-group"
nginx_log_stream = "nginx-log-stream"
